version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: threed_planner_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: threed_planner
      POSTGRES_USER: threed_planner
      POSTGRES_PASSWORD: 3dAdmin!!!
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
